project_id = "el-faraon"

[auth]
site_url = "https://elfaraoncatering.com.ar"
additional_redirect_urls = [
  "https://elfaraoncatering.com.ar/admin/",
  "http://localhost:4321/admin/",
]
password_requirements = "letters_digits"

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[functions.publish-menu-changes]
verify_jwt = false
